### ISSUE TITLE
some missing files

### ISSUE THREAD

**Issue by Gianbacchio** [batu92k/STL-Viewer#1]
Hi,
your STL viewer is very interesting and helpful, thank you for your effort.
Unfortunately, I've found troubles in opening it using Visual Studio.
I noticed that:

In the directory "triangle_mesh 1" is missing the file "triangle_mesh 1.csproj"
in the directory /bin/debug are missing the Tao*.dll
pls, let me know if I'm wrong.
regards
Giancarlo
[missing files.zip](https://github.com/batu92k/STL-Viewer/files/1877030/missing.files.zip)

**Comment by batu92k** [comment]
Hello Giancarlo

Thanks for your message, I checked the repository and I just noticed there was a problem.
I fixed the project files and the *.gitignore file. I think problem is solved.

Kind Regards
Batuhan
