### ISSUE TITLE
Incompatible licenses?

### ISSUE THREAD

**Issue by paireks** [batu92k/STL-Viewer#16]
Hey! :)

If I see correctly Mouse-Orbit submodule is on GPL 3 license while STL Viewer is Apache 2.0. I'm not sure if it can work this way, if I understand this statetment: https://www.apache.org/licenses/GPL-compatibility.html - you cannot use the GPL 3 software in a software on Apache 2.0. Please let me know if I'm wrong. Generally I'd suggest to stick to one of them in both projects to make it easier to know what can be done with it :)

**Comment by batu92k** [comment]
Hi there!

You are right! Looks like it's been some time since these repositories are out there and I didn't notice. :)
I think I will just change both of them to MIT license, it's also easier for those who want to use the project(s).
Thanks for letting me know, I will change them right away.

**Comment by batu92k** [comment]
Should be alright now. :)

**Comment by paireks** [comment]
Great! Thank you! :)
