### ISSUE TITLE
Light and camera

### ISSUE THREAD

**Issue by GBEY0402** [batu92k/STL-Viewer#3]
Apparently the code for the second light source does nothing, no second light source at all. Setting the camera height seems not to be available too.

**Comment by batu92k** [comment]
Well there is a second light source and it is illuminating the object. You can see the difference easily if you just commented out **`Gl.glEnable(Gl.GL_LIGHT1);`** command and run the program.
About the camera height stuff; I never use the camera settings before so I dont know about that part.
