### ISSUE TITLE
missing file Orbiter.cs

### ISSUE THREAD

**Issue by TanhuanHUST** [batu92k/STL-Viewer#4]

**Comment by batu92k** [comment]
Hi, here are some solutions for you.
1. **Proper way to do it:** You can update the Mouse Orbit submodule with "git submodule update --init" to have **orbiter.cs** by using your git bash terminal.
2. **A way to make it work:** The orbiter.cs file is inside this https://github.com/batu92k/Mouse-Orbit  repository, so you can just download it then add **orbiter.cs** by yourself.

I definitely suggest going with the **Solution 1**. You can take a look at how to use and update Git Submodules on the web.

Cheers
Batu

**Comment by TanhuanHUST** [comment]
> Hi, here are some solutions for you.
> 
> 1. **Proper way to do it:** You can update the Mouse Orbit submodule with "git submodule update --init" to have **orbiter.cs** by using your git bash terminal.
> 2. **A way to make it work:** The orbiter.cs file is inside this https://github.com/batu92k/Mouse-Orbit  repository, so you can just download it then add **orbiter.cs** by yourself.
> 
> I definitely suggest going with the **Solution 1**. You can take a look at how to use and update Git Submodules on the web.
> 
> Cheers
> Batu

sorry about my careless，I have fond the file and got the .exe file.  nice job!
