### ISSUE TITLE
how to save stl as bitmap or image?

### ISSUE THREAD

**Issue by alexgman** [batu92k/STL-Viewer#8]
I'm using this library in order to render an STL:

https://github.com/batu92k/STL-Viewer

It works nicely:

[![enter image description here][1]][1]

**How do we convert this STL into a BITMAP or IMAGE?**

[This method][2] is responsible for generating the STL:

        private void ReadSelectedFile(string fileName)
        {
            STLReader stlReader = new STLReader(fileName);
            TriangleMesh[] meshArray = stlReader.ReadFile();
            modelVAO = new Batu_GL.VAO_TRIANGLES();
            modelVAO.parameterArray = STLExport.Get_Mesh_Vertices(meshArray);
            modelVAO.normalArray = STLExport.Get_Mesh_Normals(meshArray);
            modelVAO.color = Color.Crimson;

            minPos = stlReader.GetMinMeshPosition(meshArray);
            maxPos = stlReader.GetMaxMeshPosition(meshArray);
            orb.Reset_Orientation();
            orb.Reset_Pan();
            orb.Reset_Scale();

            if (stlReader.Get_Process_Error())
            { 
                modelVAO = null;
                /* if there is an error, deinitialize the gl monitor to clear the screen */
                Batu_GL.Configure(GL_Monitor, Batu_GL.Ortho_Mode.CENTER);
                GL_Monitor.SwapBuffers();
            }

        }

**How do generate an image/bitmap and save it?**

  [1]: https://i.stack.imgur.com/MGQJp.png
  [2]: https://github.com/batu92k/STL-Viewer/blob/master/STL-Viewer/AppMainForm.cs

**Comment by alexgman** [comment]
@batu92k i would be so grateful if you could help with the issue above

**Comment by batu92k** [comment]
Hi @alexgman , looks like it's a feature candidate. I think we can get the capture of the current OpenGL monitor object as bitmap etc. and save it. Let me see what I can do.
But you could get the picture with the snipping tool even though it's a little bit of effort to use it. Can you tell me how you imagine using this feature, like clicking the toolbar on top and save as a bitmap to a path?

**Comment by alexgman** [comment]
Thanks so much for your response and this great software. When the user
clicks "save as image" button, the save dialog pops up, and you can save as
jpeg or bitmap. Something like that.

**Comment by batu92k** [comment]
Hi @alexgman, I attached a test version for the capture/screenshot feature :) Could you please test and write feedback here? 

[STL-Viewer-Capture-Test.zip](https://github.com/batu92k/STL-Viewer/files/10198348/STL-Viewer-Capture-Test.zip)

**Comment by alexgman** [comment]
tested! this is wonderful. thank you so much

**Comment by batu92k** [comment]
No problem! I also think it's a nice addition to the program :)
